name: "Setup Environment"
description: "Sets up the environment with yarn, Node.js, turbo, and Compact compiler"

inputs:
  skip-compact:
    description: "Skip Compact compiler installation"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@cda201ff2b32699a2ae9f59704db029e3dde4fbd # v2.3.5

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

    - name: Install Turbo Globally
      shell: bash
      env:
        TURBO_MAJOR_VERSION: 2
        TURBO_TELEMETRY_DISABLED: 1
      run: npm install turbo@${{ env.TURBO_MAJOR_VERSION }} -g

    - name: Setup Compact Compiler
      if: ${{ inputs.skip-compact != 'true' }}
      uses: midnightntwrk/setup-compact-action@4130145456ad3f45934788dd4a65647eb283e658 # loose commit/not released
      with:
        compact-version: "0.26.0"
