blank_issues_enabled: false
contact_links:
  - name: OpenZeppelin Midnight Contracts Community Support
    url: https://github.com/OpenZeppelin/midnight-contracts/discussions
    about: Please ask and answer questions here.
