:fungible-tokens: https://docs.openzeppelin.com/contracts/5.x/tokens#different-kinds-of-tokens[fungible tokens]
:eip-20: https://eips.ethereum.org/EIPS/eip-20[EIP-20]

= FungibleToken

FungibleToken is a specification for {fungible-tokens},
a type of token where all the units are exactly equal to each other.
This module is an approximation of {eip-20} written in the Compact programming language for the Midnight network.

== ERC20 Compatbility

Even though Midnight is not EVM-compatible, this implementation attempts to be an approximation of the standard.
Some features and behaviors are either not possible, not possible yet, or changed because of the vastly different tech stack
and Compact language constraints.

**Notable changes**

- **Uint<128> as value type** - Since 256-bit unsigned integers are not supported, the library uses the Compact type `Uint<128>`.

**Features and specifications NOT supported**

- **Events** - Midnight does not currently support events, but this is planned on being supported in the future.
- **Uint256 type** - There's ongoing research on ways to support uint256 in the future.
- **Interface** - Compact currently does not have a way to define a contract interface.
This library offers modules of contracts with free floating circuits; nevertheless, there's no means of enforcing that all circuits are provided.

== Contract-to-contract calls

Contract-to-contract calls are currently not supported in the Compact language.
Due to this limitation, the current iteration of FungibleToken disallows transfers and mints to the `ContractAddress` type.
Transferring tokens to a contract may result in those tokens being locked forever.
The FungibleToken module, however, does provide `unsafe` circuit variants for users who wish to experiment with sending tokens to contracts.

WARNING: The `unsafe` circuits will eventually be deprecated after Compact supports contract-to-contract calls—meaning
`transfer`, `_mint`, etc. are planned to eventually allow the recipients to be of the `ContractAddress` type.

== Usage

Import the FungibleToken module into the implementing contract.
It's recommended to prefix the module with `FungibleToken_` to avoid ccircuit signature clashes.

```typescript
// MyFungibleToken.compact
pragma language_version >= 0.15.0;

import CompactStandardLibrary;
import "./node_modules/@openzeppelin-compact/tokens/FungibleToken" prefix FungibleToken_;

constructor(
  name: Opaque<"string">,
  symbol: Opaque<"string">,
  decimals:Uint<8>
) {
  FungibleToken_initialize(name, symbol, decimals);
}
```
