name: Format and Lint

env:
  TURBO_TELEMETRY_DISABLED: 1

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Recommended by turbo team

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format & Lint
        run: turbo fmt-and-lint:ci
