name: Format, Lint, Type Check

env:
  TURBO_TELEMETRY_DISABLED: 1

on:
  push
    # paths:
    #   - '**.ts'
    #   - '**.json'

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Recommended by turbo team

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format & Lint
        run: yarn biome ci . --no-errors-on-unmatched && turbo fmt:ci

      - name: Run type checks
        run: turbo types