name: Contracts Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TURBO_TELEMETRY_DISABLED: 1

concurrency:
  group: contracts-build-${{ github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Compact Contracts
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
         fetch-depth: 2 # Recommended by turbo team

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
         skip-compile: 'true'
      
      - name: Install Compact compiler
        id: setup
        shell: bash
        run: |
            # Set version variables
            COMPILER_VERSION="0.23.0"
            LANGUAGE_VERSION="0.15.0"

            # Create directory for compiler
            COMPACT_HOME="$HOME/compactc"
            mkdir -p "$COMPACT_HOME"
            cd "$COMPACT_HOME"

            echo "⬇️ Downloading Compact compiler..."
            cd "$COMPACT_HOME"
            curl -L https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPILER_VERSION}/compactc_v${COMPILER_VERSION}_x86_64-unknown-linux-musl.zip -o compactc.zip
            unzip compactc.zip
            chmod +x compactc.bin zkir compactc

            # Verify installation
            [ -f "$COMPACT_HOME/compactc" ] || { echo "::error::❌ Failed to install compiler - compactc not found"; exit 1; }

            # Test installation
            "$COMPACT_HOME/compactc" --version

            # Set up environment variables
            echo "COMPACT_HOME=$COMPACT_HOME" >> $GITHUB_ENV
            echo "$COMPACT_HOME" >> $GITHUB_PATH

      - name: Build contracts
        run: yarn build
        timeout-minutes: 10

      - name: Check if build artifacts exist
        run: |
          if ! find contracts -type d -name artifacts | grep -q . && [ ! -d "packages/compact/dist" ]; then
            echo "::error::❌ Build artifacts not found in any contracts/*/artifacts or in packages/compact/dist!"
            exit 1
          fi
          
          # List build artifacts
          echo "✅ Build artifacts found:"
          echo "Package build artifacts (dist):"
          find contracts -name "dist" -type d -exec ls -la {} \;
          echo -e "\nCompact code artifacts (src/artifacts):"
          find contracts -name "artifacts" -type d -exec ls -la {} \;

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Build failed. Cleaning up..."
          rm -rf contracts/*/dist/
          rm -rf contracts/*/src/artifacts/