name: Contracts Version

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: contracts-version-${{ github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check Contract Versions
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Recommended by turbo team

      - name: Install Compact compiler
        id: setup
        shell: bash
        run: |
            # Set version variables
            COMPILER_VERSION="0.23.0"
            LANGUAGE_VERSION="0.15.0"

            # Create directory for compiler
            COMPACT_HOME="$HOME/compactc"
            mkdir -p "$COMPACT_HOME"
            cd "$COMPACT_HOME"

            echo "⬇️ Downloading Compact compiler..."
            cd "$COMPACT_HOME"
            curl -L https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPILER_VERSION}/compactc_v${COMPILER_VERSION}_x86_64-unknown-linux-musl.zip -o compactc.zip
            unzip compactc.zip
            chmod +x compactc.bin zkir compactc

            # Verify installation
            [ -f "$COMPACT_HOME/compactc" ] || { echo "::error::❌ Failed to install compiler - compactc not found"; exit 1; }

            # Test installation
            "$COMPACT_HOME/compactc" --version

            # Set up environment variables
            echo "COMPACT_HOME=$COMPACT_HOME" >> $GITHUB_ENV
            echo "$COMPACT_HOME" >> $GITHUB_PATH

      - name: Check compiler version
        run: |
          EXPECTED_COMPILER_VERSION="0.23.0"
          COMPILER_OUTPUT=$("$COMPACT_HOME/compactc" --version)
          COMPILER_VERSION=$(echo "$COMPILER_OUTPUT" | grep -oP '\b0\.[0-9]+\.[0-9]+\b' | head -n 1)
          if [ "$COMPILER_VERSION" != "$EXPECTED_COMPILER_VERSION" ]; then
            errMsg="❌ Compiler version mismatch!%0AExpected: $EXPECTED_COMPILER_VERSION%0AGot: $COMPILER_VERSION"
            echo "::error::$errMsg"
            exit 1
          fi
          echo "✅ Compiler version matches: $COMPILER_VERSION"

      - name: Check language version
        run: |
          EXPECTED_LANGUAGE_VERSION="0.15.0"
          LANGUAGE_OUTPUT=$("$COMPACT_HOME/compactc" --language-version)
          LANGUAGE_VERSION=$(echo "$LANGUAGE_OUTPUT" | grep -oP '\b0\.[0-9]+\.[0-9]+\b' | tail -n 1)
          if [ "$LANGUAGE_VERSION" != "$EXPECTED_LANGUAGE_VERSION" ]; then
            errMsg="❌ Language version mismatch!%0AExpected: $EXPECTED_LANGUAGE_VERSION%0AGot: $LANGUAGE_VERSION"
            echo "::error::$errMsg"
            exit 1
          fi
          echo "✅ Language version matches: $LANGUAGE_VERSION"

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Version check failed. Cleaning up..."
          rm -rf contracts/*/src/artifacts/