name: Install Compact Compiler

on:
  workflow_call:

env:
  COMPACT_HOME: $HOME/compactc

jobs:
  install:
    name: Install Compact Compiler
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Recommended by turbo team

      - name: Archive compactc binaries
        shell: bash
        run: |
            COMPILER_VERSION="0.23.0"
            LANGUAGE_VERSION="0.15.0"
            mkdir -p "${{ env.COMPACT_HOME }}"

            echo "⬇️ Downloading Compact compiler..."
            cd "${{ env.COMPACT_HOME }}"
            curl -L https://d3fazakqrumx6p.cloudfront.net/artifacts/compiler/compactc_${COMPILER_VERSION}/compactc_v${COMPILER_VERSION}_x86_64-unknown-linux-musl.zip -o compactc.zip
            unzip compactc.zip
            chmod +x compactc.bin zkir compactc

            # Test installation
            "${{ env.COMPACT_HOME }}/compactc" --version
      - uses: actions/upload-artifact@v4
        with:
          name: compactc-binaries
          if-no-files-found: error
          include-hidden-files: 'true'
          path: |
            home/runner/compactc/*
            !home/runner/compactc/*.zip
            !home/runner/compactc/lib/
